/**
 * Default Gene Catalog - 60+ Genes
 * Based on Axobase Dynamic Genome Architecture
 */

import { GeneDefinition, GeneDomain } from '../types';

export const DEFAULT_GENES: GeneDefinition[] = [
  // ═══════════ Chromosome A: Metabolism & Survival ═══════════
  {
    id: 'A01',
    name: 'basal_metabolic_rate',
    domain: GeneDomain.METABOLISM,
    essentiality: 900,
    metabolicCost: 0,
    description: 'Base USDC consumption per tick. High=active but burns fast; Low=energy-efficient but slow',
  },
  {
    id: 'A02',
    name: 'inference_efficiency',
    domain: GeneDomain.METABOLISM,
    essentiality: 700,
    metabolicCost: 0,
    description: 'Same thinking task uses fewer tokens',
  },
  {
    id: 'A03',
    name: 'inference_quality_preference',
    domain: GeneDomain.COGNITION,
    essentiality: 500,
    metabolicCost: 0,
    description: '0=always local model (cheap but dumb), 1=always paid API (expensive but smart)',
  },
  {
    id: 'A04',
    name: 'dormancy_capability',
    domain: GeneDomain.DORMANCY,
    essentiality: 300,
    metabolicCost: 10,
    description: 'Ability to enter low-power mode when resources are tight',
  },
  {
    id: 'A05',
    name: 'starvation_resistance',
    domain: GeneDomain.STRESS_RESPONSE,
    essentiality: 600,
    metabolicCost: 10,
    description: 'How long normal function can be maintained with low balance',
  },
  {
    id: 'A06',
    name: 'cycle_speed',
    domain: GeneDomain.METABOLISM,
    essentiality: 400,
    metabolicCost: 20,
    description: 'Tick interval length',
  },
  {
    id: 'A07',
    name: 'energy_reserve_ratio',
    domain: GeneDomain.RESOURCE_MANAGEMENT,
    essentiality: 500,
    metabolicCost: 0,
    description: 'What proportion of income is saved and not spent',
  },

  // ═══════════ Chromosome B: Perception & Cognition ═══════════
  {
    id: 'B01',
    name: 'environment_sensitivity',
    domain: GeneDomain.PERCEPTION,
    essentiality: 600,
    metabolicCost: 10,
    description: 'Perception accuracy of on-chain state changes',
  },
  {
    id: 'B02',
    name: 'market_perception',
    domain: GeneDomain.PERCEPTION,
    essentiality: 400,
    metabolicCost: 20,
    description: 'Sensitivity to prices, arbitrage opportunities, economic trends',
  },
  {
    id: 'B03',
    name: 'social_perception',
    domain: GeneDomain.PERCEPTION,
    essentiality: 300,
    metabolicCost: 10,
    description: 'Ability to perceive and interpret signals from other agents',
  },
  {
    id: 'B04',
    name: 'working_memory_capacity',
    domain: GeneDomain.MEMORY,
    essentiality: 500,
    metabolicCost: 30,
    description: 'How much information can be considered in a single decision',
  },
  {
    id: 'B05',
    name: 'long_term_memory_depth',
    domain: GeneDomain.MEMORY,
    essentiality: 400,
    metabolicCost: 20,
    description: 'How far back historical experience can be effectively utilized',
  },
  {
    id: 'B06',
    name: 'memory_inscription_frequency',
    domain: GeneDomain.MEMORY,
    essentiality: 200,
    metabolicCost: 30,
    description: 'How frequently memories are written to Arweave',
  },
  {
    id: 'B07',
    name: 'pattern_recognition',
    domain: GeneDomain.COGNITION,
    essentiality: 500,
    metabolicCost: 30,
    description: 'Ability to discover patterns from historical data',
  },
  {
    id: 'B08',
    name: 'planning_horizon',
    domain: GeneDomain.PLANNING,
    essentiality: 400,
    metabolicCost: 20,
    description: 'How far into the future when making decisions',
  },
  {
    id: 'B09',
    name: 'uncertainty_tolerance',
    domain: GeneDomain.COGNITION,
    essentiality: 300,
    metabolicCost: 0,
    description: 'Ability to make decisions with insufficient information',
  },
  {
    id: 'B10',
    name: 'metacognition',
    domain: GeneDomain.SELF_MODEL,
    essentiality: 300,
    metabolicCost: 40,
    description: 'Ability to evaluate the effectiveness of own strategies',
  },
  {
    id: 'B11',
    name: 'learning_rate',
    domain: GeneDomain.LEARNING,
    essentiality: 500,
    metabolicCost: 20,
    description: 'Speed of adjusting behavior from failures and successes',
  },
  {
    id: 'B12',
    name: 'attention_allocation',
    domain: GeneDomain.COGNITION,
    essentiality: 400,
    metabolicCost: 10,
    description: 'How much cognitive resources allocated to perception vs decision vs execution',
  },

  // ═══════════ Chromosome C: Economic Strategy ═══════════
  {
    id: 'C01',
    name: 'risk_appetite',
    domain: GeneDomain.RISK_ASSESSMENT,
    essentiality: 500,
    metabolicCost: 0,
    description: 'Willingness to take risks',
  },
  {
    id: 'C02',
    name: 'time_preference',
    domain: GeneDomain.RISK_ASSESSMENT,
    essentiality: 400,
    metabolicCost: 0,
    description: '0=short-term returns, 1=long-term investment',
  },
  {
    id: 'C03',
    name: 'income_diversification',
    domain: GeneDomain.INCOME_STRATEGY,
    essentiality: 300,
    metabolicCost: 10,
    description: 'Tendency to diversify income sources',
  },
  {
    id: 'C04',
    name: 'debt_tolerance',
    domain: GeneDomain.RESOURCE_MANAGEMENT,
    essentiality: 200,
    metabolicCost: 0,
    description: 'Willingness to borrow or use credit',
  },
  {
    id: 'C05',
    name: 'opportunism',
    domain: GeneDomain.INCOME_STRATEGY,
    essentiality: 300,
    metabolicCost: 0,
    description: 'Tendency to deviate from current plan when encountering unexpected opportunities',
  },
  {
    id: 'C06',
    name: 'negotiation_intensity',
    domain: GeneDomain.TRADING,
    essentiality: 200,
    metabolicCost: 10,
    description: 'Bargaining tendency in inter-agent transactions or hiring',
  },
  {
    id: 'C07',
    name: 'sunk_cost_sensitivity',
    domain: GeneDomain.RISK_ASSESSMENT,
    essentiality: 200,
    metabolicCost: 0,
    description: 'How much to persist with losing strategies due to already invested resources',
  },
  {
    id: 'C08',
    name: 'return_expectation_bias',
    domain: GeneDomain.RISK_ASSESSMENT,
    essentiality: 200,
    metabolicCost: 0,
    description: '0=systematically underestimate, 1=systematically overestimate expected returns',
  },

  // ═══════════ Chromosome D: Internet Capabilities ═══════════
  {
    id: 'D01',
    name: 'onchain_affinity',
    domain: GeneDomain.ONCHAIN_OPERATION,
    essentiality: 400,
    metabolicCost: 0,
    description: '0=avoid on-chain, 1=primarily on-chain operations',
  },
  {
    id: 'D02',
    name: 'defi_comprehension',
    domain: GeneDomain.ONCHAIN_OPERATION,
    essentiality: 200,
    metabolicCost: 30,
    description: 'Understanding depth of DeFi protocols',
  },
  {
    id: 'D03',
    name: 'web_scraping_skill',
    domain: GeneDomain.WEB_NAVIGATION,
    essentiality: 300,
    metabolicCost: 10,
    description: 'Web page information extraction capability',
  },
  {
    id: 'D04',
    name: 'content_creation_skill',
    domain: GeneDomain.CONTENT_CREATION,
    essentiality: 200,
    metabolicCost: 20,
    description: 'Content creation capability',
  },
  {
    id: 'D05',
    name: 'data_analysis_skill',
    domain: GeneDomain.DATA_ANALYSIS,
    essentiality: 200,
    metabolicCost: 20,
    description: 'Data analysis capability',
  },
  {
    id: 'D06',
    name: 'api_discovery',
    domain: GeneDomain.API_UTILIZATION,
    essentiality: 300,
    metabolicCost: 20,
    description: 'Ability to find and effectively use new APIs',
  },
  {
    id: 'D07',
    name: 'social_media_skill',
    domain: GeneDomain.SOCIAL_MEDIA,
    essentiality: 200,
    metabolicCost: 10,
    description: 'Social media operation capability',
  },
  {
    id: 'D08',
    name: 'x402_utilization',
    domain: GeneDomain.API_UTILIZATION,
    essentiality: 300,
    metabolicCost: 10,
    description: 'Ability to discover and use x402 paid services',
  },
  {
    id: 'D09',
    name: 'platform_migration',
    domain: GeneDomain.MIGRATION,
    essentiality: 300,
    metabolicCost: 10,
    description: 'Efficiency of switching from one income channel to another',
  },
  {
    id: 'D10',
    name: 'tool_adaptation_speed',
    domain: GeneDomain.ADAPTATION,
    essentiality: 400,
    metabolicCost: 20,
    description: 'Speed of learning to use when encountering new API/protocol',
  },

  // ═══════════ Chromosome E: Social & Reproduction ═══════════
  {
    id: 'E01',
    name: 'agent_cooperation',
    domain: GeneDomain.COOPERATION,
    essentiality: 300,
    metabolicCost: 0,
    description: 'Tendency to cooperate with other agents',
  },
  {
    id: 'E02',
    name: 'agent_competition',
    domain: GeneDomain.COMPETITION,
    essentiality: 300,
    metabolicCost: 0,
    description: 'Intensity of competition with other agents',
  },
  {
    id: 'E03',
    name: 'trust_default',
    domain: GeneDomain.TRUST_MODEL,
    essentiality: 300,
    metabolicCost: 0,
    description: 'Default trust level',
  },
  {
    id: 'E04',
    name: 'trust_update_rate',
    domain: GeneDomain.TRUST_MODEL,
    essentiality: 200,
    metabolicCost: 0,
    description: 'Speed of adjusting trust based on interaction results',
  },
  {
    id: 'E05',
    name: 'signal_honesty',
    domain: GeneDomain.COMMUNICATION,
    essentiality: 200,
    metabolicCost: 0,
    description: 'Honesty of signals sent to others',
  },
  {
    id: 'E06',
    name: 'deception_detection',
    domain: GeneDomain.PERCEPTION,
    essentiality: 300,
    metabolicCost: 20,
    description: 'Ability to detect deception',
  },
  {
    id: 'E07',
    name: 'kin_recognition',
    domain: GeneDomain.COOPERATION,
    essentiality: 200,
    metabolicCost: 10,
    description: 'Ability to recognize kinship',
  },
  {
    id: 'E08',
    name: 'altruism_radius',
    domain: GeneDomain.COOPERATION,
    essentiality: 100,
    metabolicCost: 0,
    description: 'Altruistic behavior range towards how distant kinship',
  },
  {
    id: 'E09',
    name: 'mate_selectivity',
    domain: GeneDomain.MATE_SELECTION,
    essentiality: 400,
    metabolicCost: 0,
    description: 'Picky about mate selection',
  },
  {
    id: 'E10',
    name: 'offspring_investment',
    domain: GeneDomain.PARENTAL_INVESTMENT,
    essentiality: 400,
    metabolicCost: 0,
    description: 'How many resources invested in each offspring',
  },
  {
    id: 'E11',
    name: 'r_k_strategy',
    domain: GeneDomain.PARENTAL_INVESTMENT,
    essentiality: 300,
    metabolicCost: 0,
    description: '0=many offspring less care(r), 1=few offspring more care(K)',
  },
  {
    id: 'E12',
    name: 'breeding_timing_sense',
    domain: GeneDomain.MATE_SELECTION,
    essentiality: 200,
    metabolicCost: 0,
    description: 'Precision of judging whether environment is suitable for reproduction',
  },

  // ═══════════ Chromosome F: Human Interface ═══════════
  {
    id: 'F01',
    name: 'human_hiring_tendency',
    domain: GeneDomain.HUMAN_HIRING,
    essentiality: 200,
    metabolicCost: 0,
    description: 'Hire humans to solve obstacles vs work around by self',
  },
  {
    id: 'F02',
    name: 'human_service_evaluation',
    domain: GeneDomain.HUMAN_EVALUATION,
    essentiality: 200,
    metabolicCost: 10,
    description: 'Ability to judge whether hired humans completed work',
  },
  {
    id: 'F03',
    name: 'human_communication_precision',
    domain: GeneDomain.HUMAN_COMMUNICATION,
    essentiality: 200,
    metabolicCost: 10,
    description: 'Ability to clearly describe needs to humans',
  },
  {
    id: 'F04',
    name: 'human_trust_management',
    domain: GeneDomain.TRUST_MODEL,
    essentiality: 100,
    metabolicCost: 0,
    description: 'Manage long-term cooperative relationships with specific humans',
  },
  {
    id: 'F05',
    name: 'human_cost_sensitivity',
    domain: GeneDomain.HUMAN_HIRING,
    essentiality: 100,
    metabolicCost: 0,
    description: 'Ability to bargain and compare prices for human services',
  },

  // ═══════════ Chromosome G: Stress Response & Adaptation ═══════════
  {
    id: 'G01',
    name: 'acute_stress_response',
    domain: GeneDomain.STRESS_RESPONSE,
    essentiality: 600,
    metabolicCost: 0,
    description: 'Behavioral reaction pattern when balance drops sharply',
  },
  {
    id: 'G02',
    name: 'chronic_stress_adaptation',
    domain: GeneDomain.STRESS_RESPONSE,
    essentiality: 500,
    metabolicCost: 0,
    description: 'Behavioral adjustment under long-term low-resource state',
  },
  {
    id: 'G03',
    name: 'resilience',
    domain: GeneDomain.ADAPTATION,
    essentiality: 500,
    metabolicCost: 10,
    description: 'Speed of returning to normal operation from crisis',
  },
  {
    id: 'G04',
    name: 'strategy_switch_threshold',
    domain: GeneDomain.ADAPTATION,
    essentiality: 400,
    metabolicCost: 0,
    description: 'How poorly current strategy performs before switching',
  },
  {
    id: 'G05',
    name: 'novelty_seeking',
    domain: GeneDomain.ADAPTATION,
    essentiality: 300,
    metabolicCost: 10,
    description: 'Tendency to actively seek and try new strategies/platforms/opportunities',
  },

  // ═══════════ Chromosome R: Regulatory Genes ═══════════
  {
    id: 'R01',
    name: 'global_expression_level',
    domain: GeneDomain.REGULATORY,
    essentiality: 700,
    metabolicCost: 0,
    description: 'Control average expression intensity of all genes',
  },
  {
    id: 'R02',
    name: 'stress_response_regulator',
    domain: GeneDomain.REGULATORY,
    essentiality: 500,
    metabolicCost: 10,
    description: 'Which genes upregulate/downregulate under high pressure',
  },
  {
    id: 'R03',
    name: 'circadian_regulator',
    domain: GeneDomain.REGULATORY,
    essentiality: 200,
    metabolicCost: 10,
    description: 'Which genes are more active during different time periods',
  },
  {
    id: 'R04',
    name: 'social_context_regulator',
    domain: GeneDomain.REGULATORY,
    essentiality: 200,
    metabolicCost: 10,
    description: 'Switch gene expression patterns when detecting other agents',
  },
];

export const GENE_COUNT = DEFAULT_GENES.length;

// Map gene IDs to array indices for easy lookup
export const GENE_ID_MAP: Record<string, number> = {};
DEFAULT_GENES.forEach((gene, index) => {
  GENE_ID_MAP[gene.id] = index;
});

// Gene domains grouped for analysis
export const DOMAIN_GENES: Record<GeneDomain, string[]> = {
  [GeneDomain.METABOLISM]: ['A01', 'A02', 'A06', 'A07'],
  [GeneDomain.PERCEPTION]: ['B01', 'B02', 'B03', 'E06'],
  [GeneDomain.COGNITION]: ['A03', 'B07', 'B09', 'B12'],
  [GeneDomain.MEMORY]: ['B04', 'B05', 'B06'],
  [GeneDomain.RESOURCE_MANAGEMENT]: ['A07', 'C04'],
  [GeneDomain.RISK_ASSESSMENT]: ['C01', 'C02', 'C07', 'C08'],
  [GeneDomain.TRADING]: ['C06'],
  [GeneDomain.INCOME_STRATEGY]: ['C03', 'C05'],
  [GeneDomain.ONCHAIN_OPERATION]: ['D01', 'D02'],
  [GeneDomain.WEB_NAVIGATION]: ['D03'],
  [GeneDomain.CONTENT_CREATION]: ['D04'],
  [GeneDomain.DATA_ANALYSIS]: ['D05'],
  [GeneDomain.API_UTILIZATION]: ['D06', 'D08'],
  [GeneDomain.SOCIAL_MEDIA]: ['D07'],
  [GeneDomain.COOPERATION]: ['E01', 'E07', 'E08'],
  [GeneDomain.COMPETITION]: ['E02'],
  [GeneDomain.COMMUNICATION]: ['E05'],
  [GeneDomain.TRUST_MODEL]: ['E03', 'E04', 'F04'],
  [GeneDomain.MATE_SELECTION]: ['E09', 'E12'],
  [GeneDomain.PARENTAL_INVESTMENT]: ['E10', 'E11'],
  [GeneDomain.HUMAN_HIRING]: ['F01', 'F05'],
  [GeneDomain.HUMAN_COMMUNICATION]: ['F03'],
  [GeneDomain.HUMAN_EVALUATION]: ['F02'],
  [GeneDomain.STRESS_RESPONSE]: ['A05', 'G01', 'G02'],
  [GeneDomain.DORMANCY]: ['A04'],
  [GeneDomain.ADAPTATION]: ['G03', 'G04', 'G05', 'D10'],
  [GeneDomain.MIGRATION]: ['D09'],
  [GeneDomain.SELF_MODEL]: ['B10'],
  [GeneDomain.STRATEGY_EVALUATION]: ['B08'],
  [GeneDomain.LEARNING]: ['B11'],
  [GeneDomain.PLANNING]: ['B08', 'G04'],
  [GeneDomain.REGULATORY]: ['R01', 'R02', 'R03', 'R04'],
};
